"""empty message

Revision ID: e9a99fe05f1c
Revises: f1469c5291de
Create Date: 2020-02-09 21:55:56.265560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a99fe05f1c'
down_revision = 'f1469c5291de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'seeking_talent')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'phone')
    op.drop_column('artists', 'image_link')
    op.drop_column('artists', 'facebook_link')
    # ### end Alembic commands ###
