"""empty message

Revision ID: f1469c5291de
Revises: f88c122d1292
Create Date: 2020-02-09 21:37:20.652357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1469c5291de'
down_revision = 'f88c122d1292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'phone')
    op.drop_column('venues', 'image_link')
    op.drop_column('venues', 'facebook_link')
    op.drop_column('venues', 'address')
    # ### end Alembic commands ###
