"""empty message

Revision ID: f4535bad4a28
Revises: e9a99fe05f1c
Create Date: 2020-02-09 22:07:31.127813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4535bad4a28'
down_revision = 'e9a99fe05f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String(length=20)), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String(length=20)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###
