"""empty message

Revision ID: f88c122d1292
Revises: 
Create Date: 2020-02-07 12:24:52.476962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88c122d1292'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artists', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'city_id')
    # ### end Alembic commands ###
